<?php

/**
 * @file
 * Primary module hooks for WiDS Pune Core module.
 *
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function widspune_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $user = \Drupal::currentUser();
  $check_against = ['administrator', 'editor'];
  $roles = $user->getRoles();
  $result = array_intersect($check_against, $roles);

  $form['field_bio']['#access'] = FALSE;
  $form['field_photo_with_frame']['#access'] = FALSE;
  $form['field_speaker_order']['#access'] = FALSE;
  $form['field_volunteer_order']['#access'] = FALSE;

  if ($user->id() == 1 || !empty($result)) {
    $form['field_bio']['#access'] = TRUE;
    $form['field_photo_with_frame']['#access'] = TRUE;
    $form['field_speaker_order']['#access'] = TRUE;
    $form['field_volunteer_order']['#access'] = TRUE;
  }
}
