module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_importer: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  faqfield: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flickr: 0
  flickr_api: 0
  flickr_colorbox: 0
  flickr_filter: 0
  help: 0
  history: 0
  image: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_attributes: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  remove_username: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  smtp: 0
  social_media_links: 0
  social_media_links_field: 0
  superfish: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  time_field: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_taxonomy_term_name_into_id: 0
  views_ui: 0
  widspune: 0
  fontyourface: 1
  menu_link_content: 1
  pathauto: 1
  google_fonts_api: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  widspune20: 0
  widspune: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
