enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Actor&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=News Cycle&subset=latin#700'
  - 'https://www.google.com/webfonts/family?family=News Cycle&subset=latin#regular'
  - 'https://www.google.com/webfonts/family?family=Montserrat&subset=latin#300'
load_all_enabled_fonts: 1
_core:
  default_config_hash: r8uAx4mTBwCkgDFbdKCmhjgbb91BQ4HbWSYRKrlowMY
