smtp_on: true
smtp_host: widspunecom.mailserverone.com
smtp_hostbackup: ''
smtp_port: '25'
smtp_protocol: tls
smtp_username: conference-widspune
smtp_password: 'Conf#8888ne'
smtp_from: womenindatascience_pune@widspune.com
smtp_fromname: 'WiDS Pune'
smtp_client_hostname: ''
smtp_client_helo: Hello
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: true
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
