schemas:
  bootstrap: 8000
  widspune20: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'https://wids-pune.lndo.site/themes/custom/widspune20/favicon.ico'
  use_default: true
logo:
  path: 'public://widspunelogo_1_0.png'
  url: ''
  use_default: false
fluid_container: 1
table_responsive: '-1'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  page_banner: ''
  content_top: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  content_bottom: ''
  footer_top: ''
  footer_left: ''
  footer_center: ''
  footer_right: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
forms_smart_descriptions: 0
