favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://wids-pune.lndo.site/themes/custom/widspune/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  widspune: 8000
fluid_container: 1
table_responsive: '-1'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  page_banner: ''
  content_top: ''
  content: ''
  sidebar_first: ''
  sidebar_second: ''
  content_bottom: ''
  footer: ''
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
logo:
  path: 'public://widspunelogo.png'
  url: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
