<?php

/**
 * @file
 * Provides a rsvp confirm entity type.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function rsvp_confirm_theme() {
  return [
    'rsvp_confirm' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for rsvp confirm templates.
 *
 * Default template: rsvp-confirm.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the rsvp confirm information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_rsvp_confirm(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_mail().
 */
function rsvp_confirm_mail($key, &$message, $params) {
  $message['from'] = \Drupal::config('system.site')->get('mail');
  switch ($key) {
    case 'rsvp_confirm':
      $message['subject'] = t('RSVP accepted: @title', ['@title' =>
      $params['node_title']]);
      $message['body'][] = $params['message'];
    break;

    case 'rsvp_cancel':
      $message['subject'] = t('RSVP cancelled: @title', ['@title' =>
        $params['node_title']]);
      $message['body'][] = $params['message'];
      break;

  }
}


